- hosts: me
  roles:
    - role: defaults
    - role: brew
    - role: lang
      vars:
        opts:
          go: darwin amd64
          node: darwin-x64
          php: -- --with-bz2=/usr/local/opt/bzip2 --with-curl=/usr/local/opt/curl
