version: "3.8"

x-ansible-default-config: &ansible-default-config
  build: .
  volumes:
    - .:/src/:ro
    - ~/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro
  environment:
    - ANSIBLE_INVENTORY=/src/hosts
    - ANSIBLE_HOST_KEY_CHECKING=False
    - ANSIBLE_USE_PERSISTENT_CONNECTIONS=True
    - ANSIBLE_REMOTE_USER=${USER}
    - ANSIBLE_DISPLAY_ARGS_TO_STDOUT=True
    - ANSIBLE_DIFF_ALWAYS=True
    - ANSIBLE_PYTHON_INTERPRETER=auto_silent
    - ANSIBLE_PIPELINING=True
    - ANSIBLE_SSH_PIPELINING=True

services:
  ansible:
    <<: *ansible-default-config
  ansible-playbook:
    <<: *ansible-default-config
    entrypoint:
      - ansible-playbook
